export default function defaultFields() {
  return [
    { name: "Email", field_id: "email", type_id: 1 },
    { name: "First Name", field_id: "first_name", type_id: 1 },
    { name: "Last Name", field_id: "last_name", type_id: 1 },
    { name: "Website", field_id: "website", type_id: 1 },
    { name: "Zip", field_id: "zip", type_id: 1 },
    { name: "Years in business", field_id: "years_in_business", type_id: 1 },
    { name: "Territory", field_id: "territory", type_id: 1 },
    { name: "State", field_id: "state", type_id: 1 },
    { name: "Source", field_id: "source", type_id: 1 },
    { name: "Phone", field_id: "phone", type_id: 1 },
    { name: "Job Title", field_id: "job_title", type_id: 1 },
    { name: "Salutation", field_id: "salutation", type_id: 4 },
    { name: "Job Department", field_id: "department", type_id: 4 },
    { name: "Pardot Hard Bounced", field_id: "pardot_hard_bounced", type_id: 3 },
    { name: "Opted Out ", field_id: "opted_out", type_id: 3 },
    { name: "Department ", field_id: "department", type_id: 1 },
    { name: "Employees ", field_id: "employees", type_id: 8 },
    { name: "Industry", field_id: "industry", type_id: 1 },
    { name: "Fax", field_id: "fax", type_id: 1 },
    { name: "Fax", field_id: "fax", type_id: 1 },
    { name: "Email Bounced Reason", field_id: "email_bounced_reason", type_id: 1 },
    { name: "Email Bounced Date", field_id: "email_bounced_date", type_id: 1 },
    { name: "Country", field_id: "country", type_id: 1 },
    { name: "Company", field_id: "company", type_id: 1 },
    { name: "Is Do Not Email", field_id: "is_do_not_email", type_id: 3 },
    { name: "Is Do Call", field_id: "is_do_not_call", type_id: 3 },
    { name: "Company", field_id: "company", type_id: 1 },
    { name: "City", field_id: "city", type_id: 1 },
    { name: "Last Scored At", field_id: "last_scored_at", type_id: 12 },
    { name: "Address One", field_id: "address_one", type_id: 1 },
    { name: "Address Two", field_id: "address_two", type_id: 1 },
    { name: "Comments", field_id: "comments", type_id: 5 }
  ];
}
