export default function defaultFields() {
  return [
    { name: "Email", field_id: "email" },
    { name: "First Name", field_id: "first_name" },
    { name: "Last Name", field_id: "last_name" },
    { name: "Website", field_id: "website" },
    { name: "Zip", field_id: "zip" },
    { name: "Years in business", field_id: "years_in_business" },
    { name: "Territory", field_id: "territory" },
    { name: "State", field_id: "state" },
    { name: "Score", field_id: "score" },
    { name: "Source", field_id: "source" },
    { name: "Phone", field_id: "phone" },
    { name: "Job Title", field_id: "job_title" },
    { name: "Salutation", field_id: "salutation" },
    { name: "Pardot Hard Bounced", field_id: "pardot_hard_bounced" },
    { name: "Opted Out ", field_id: "opted_out" },
    { name: "Department ", field_id: "department" },
    { name: "Employees ", field_id: "employees" },
    { name: "Industry", field_id: "industry" },
    { name: "Fax", field_id: "fax" },
    { name: "Fax", field_id: "fax" },
    { name: "Email Bounced Reason", field_id: "email_bounced_reason" },
    { name: "Email Bounced Date", field_id: "email_bounced_date" },
    { name: "Country", field_id: "country" },
    { name: "Company", field_id: "company" },
    { name: "Is Do Not Email", field_id: "is_do_not_email" },
    { name: "Is Do Call", field_id: "is_do_not_call" },
    { name: "Company", field_id: "company" },
    { name: "City", field_id: "city" },
    { name: "Last Scored At", field_id: "last_scored_at" },
    { name: "Address One", field_id: "address_one" },
    { name: "Address Two", field_id: "address_two" }
  ];
}
